### ISSUE TITLE
Shows unnamed list

### ISSUE THREAD

**Issue by thibmaek** [uchida/alfred-switch-bluetooth#1]
<img width="714" alt="screen shot 2016-05-12 at 10 09 41" src="https://cloud.githubusercontent.com/assets/6213695/15207993/aeebe9d4-1829-11e6-97b2-ec5b024a04bf.png">

**Comment by uchida** [comment]
Thank you for reporting issue, this issue seems due to changes on `system_profiler` output.
This issue is fixed and released [new version](https://github.com/uchida/alfred-switch-bluetooth/releases/download/2016.05.12/alfred-switch-bluetooth.alfredworkflow) please try it.

**Comment by uchida** [comment]
Oops, I found a problem on new version...

**Comment by uchida** [comment]
fixed and release [new version](https://github.com/uchida/alfred-switch-bluetooth/releases/download/2016.05.12/alfred-switch-bluetooth.alfredworkflow), please try new one.
